MODULE_CONFIG GIO212 AT 3

	checkOnLoad := FALSE;
	initialize := FALSE;
	redundant := TRUE;

CHANNEL_CONFIG
	AV_T_PT100_A_nah_gelb AT %ID3.1 : DINT;
	AV_T_PT100_A_fern_rot AT %ID3.2 : DINT;
	AV_T_PT100_B_nah_blau AT %ID3.3 : DINT;
	AV_T_PT100_B_fern_schwarz AT %ID3.4 : DINT;
	Heater_A_rot AT %QD3.5 : DINT;
	Heater_B_blau AT %QD3.6 : DINT;
	FAN AT %QD3.7 : DINT;
	DO_QM01 AT %QX3.11 : BOOL;
	DO_QM02 AT %QX3.12 : BOOL;
END_CHANNEL_CONFIG

END_MODULE_CONFIG
