;Sample Configuration File
;INFO: Keywords with a leading ; are hidden keywords and can not be modified
<CPU_ALL>
[SYSTEM]
  (BootFiles)
    System = msys.o
    PreferredOS = _BootParams_
  (SysDirs)
    System = sys/
    Drivers = drv/
    Applications = app/
    Services = srv/
    Etc = etc/
    Keys = keys/
    Temporary = /ram0/
    NonVolatile = /nvram0/
  (BootHost)
    Gateway = 
    Flags = 0x0
  (Network)
    NetAddress = 192.168.178.230:ffffff00
    NetName = m200
    DhcpEnable = OFF
    NetAddress2 = 192.0.2.230:ffffff00
    NetName2 = ETH2
    DhcpEnable2 = OFF
    NetName3 = ETH3
    DhcpEnable3 = ON
;       NetTskPriority     = 97                 ;priority of network task tNet0 (tNetTask in vxw5)
;       NetTskPriority2    = 97                 ;priority of network task tNet1
;       NetTskPriority3    = 97                 ;priority of network task tNet2
    NetTskBusyPriority = 200  ;busy priority of network tasks tNet0/1/2
    UserName = M1
    Password = ********
  (SysTime)
    TimeBase = LOCAL
    TimeZone = GMT
    TickRate = 2000  ;ticks per second on MPC2xx and MP2xx
    TickSource = Timer  ;tick origin can be RTC, Timer, etc.
    TimeSlice = 2  ;ticks per time slice
    AuxRate = 0  ;aux clocks per second, 0=OFF
  (SyncRate)
    SyncHigh = 0  ;0 = OFF
    SyncLow = 0  ;0 = OFF
  (BlockDrivers)
<CPU_MX>
    NoSymlinkPcc0 = ON
    NoSymlinkCfc0 = ON
<CPU_MC>
    ram0 = 0x04000000  ;64MB
<CPU_MH>
    ram0 = 0x04000000  ;64MB
<CPU_ALL>
    ram0 = 0x00400000  ;4MB
    LongFileNames = ON
  (SerialDrivers)
    COM1Baudrate = 19200
    COM1DataBits = 8
    COM1StopBits = 1
    COM1Parity = Even
    COM1RxBuffer = 1024
    COM1TxBuffer = 1024
    COM1Handshake = None
    COM1LineMode = RS485
    COM1DriverMode = TaskMode
    COM1MaxCycle = 2000
    COM2Baudrate = 57600
    COM2DataBits = 8
    COM2StopBits = 1
    COM2Parity = None
    COM2RxBuffer = 1024
    COM2TxBuffer = 1024
    COM2Handshake = None
    COM2LineMode = RS232
    COM2DriverMode = TaskMode
    NoUSBDriver = ON
    NoUSBDevice = OFF
  (Memory)
    Partition = 1  ;for global data
<CPU_MC>
    Size = 0x00100000  ;1MB
<CPU_MH>
    Size = 0x00100000  ;1MB
<CPU_ALL>
    Size = 0x00020000  ;128KB
  (Memory)
    Partition = 2  ;for app programs
<CPU_MC>
    Size = 0x08000000  ;128MB
<CPU_MH>
    Size = 0x08000000  ;128MB
<CPU_MX>
    Size = 0x01000000  ;16MB
<CPU_MPC>
    Size = 0x01000000  ;16MB
<CPU_ALL>
    Size = 0x00100000  ;1MB
  (Debug)
    DebugMode = 0x0
    BootMode = 0x0
    NoWatchdog = OFF
    WindView = OFF
    WindDebug = OFF
;       WindSyncTimeout = 5000                  ;value in ms used by Target Agent
    NoWindShell = ON
;       WindExcHandler  = OFF
    LogFileName = /nvram0/logfile.txt
    LogFileSize = 100  ;max. number of entries (max. 1000)
    LogFileSizeKb = 10  ;max. size of logfile in kB (max. 125)
    LogSizeFixed = OFF  ;max. 80 characters per entry
    LogToConsole = ON  ;write log messages to console
    LogEnableSuppression = OFF  ;Enable suppression of identical log messages
    LogColorInfo = NORMAL  ;color of log infos on shell
    LogColorWarning = YELLOW  ;color of log warnings on shell
    LogColorError = RED  ;color of log erros on shell
  (ExcDump)
    ExcDump = OFF
  (SysMode)
    AppDevelopment = ON
    RebootOnExc = OFF
    CpuTimeInfo = OFF
    NoMemProtect = ON
    PccProgEnable = ON
    NoPccPreErase = OFF
    NoCheckDosFs = OFF  ;do not check file systems at boot time
    SecurityLevel = 0
    StackExecProtect = ON  ;enable stack execution protection
    UserManagement = ON  ;enable user management
    PasswordComplexity = OFF  ;enable password complexity checks (requires UserManagement=ON)
    LockoutThreshold = 0  ;number of failed, coherent sign-in attempts that will cause a user account to be locked (0 lockout feature disabled, 1 - 10)
    LockoutResetAfter = 0  ;number of seconds that must elapse from the time a user fails to sign in before the failed sign-in attempt counter is reset to 0 (0 no timed reset)
    LockoutDuration = 0  ;number of seconds that a locked account remains locked before automatically becoming unlocked (0 lock never removed automatically)
  (Syslog)
    EnableLogServer = OFF  ; Enables/Disables syslog functionality
  (Monitoring)
    NoWatchCpuTemp = OFF
    NoWatchCpuUsage = OFF
    NoWatchNetUsage = OFF
    NoWatchIOBus = OFF
    NoWatchAlive = OFF
    NoFlashRdyLED = OFF
    NoCheckDRam = OFF
    NoCheckStack = OFF
    MaxNetInUsage = 100  ;max ethernet input load in %
    MaxNetOutUsage = 100  ;max ethernet output load in %
  (IO-System)
    ErrorPriority = 10  ;priority of error task
    EventIntTask = ON  ;event interrupt as task
    FastBusDelay = 5  ;should be 0 without FAST-Bus
    MinStations = 1  ;minimum number of stations
    MaxStations = 16  ;maximum number of stations
    NoNewSlaveReset = OFF  ;reboot if new slaves are recognized
    NoBadSlaveReset = OFF  ;reboot if bad slaves are recognized
    ReqColdClimate = OFF  ;require cold climate components
    NoRedundantRead = ON  ;redundant read on all inputs
    NoWriteVerify = ON  ;verify writes on all outputs
  (PlcRts)
    GlobalData = 256
    RetainData = 256
    Timeouts = ON
    RetainExport = OFF
    RtiDir = app/
  (ResHandler)
    UserCheck = OFF
  (SmiHandler)
    SmiQueueSize = 10  ;max number of SMI messages each SW-module
<CPU_MC>
    SmiMaxSize = 8192  ;max size of SMI messages
<CPU_MH>
    SmiMaxSize = 8192  ;max size of SMI messages
<CPU_ALL>
    SmiMaxSize = 2048  ;max size of SMI messages
    ConnLimit = 0  ;connection limit per SMI protocol (SMI-TCP, SMI-QSOAP/SSL)
    ConnLimitMask = 0  ;connection limit mask to group hosts (0 - 32)
    ConnTimeout = 60000  ;request and connection timeout in ms
    ReplyTimeout = 3000  ;timeout in ms for all external SMI replies
    EnableUdp = ON  ;enable SMI-UDP server
    EnableTcp = ON  ;enable SMI-TCP server
    EnableQSoap = ON  ;enable SMI-QSOAP server (HTTP, HTTP forwarding)
    EnableSsl = OFF  ;enable SMI-SSL server (HTTPS, HTTPS forwarding)
    QSoapPort = 80  ;SMI-QSOAP server port (HTTP port)
    SslPort = 443  ;SMI-SSL server port (HTTPS port)
;       IntReplyTimeout = 30000                 ;timeout in ms for INIT call, default = 30s
;       EoiReplyTimeout = 30000                 ;timeout in ms for EOI call, default = 30s
  (Application)
    Name = Application_1  ;is used to describe an application
;       Cpu1Address     = 192.1.0.231
;       Cpu1Name        = Slave1
;       Cpu2Address     = 192.1.0.232
;       Cpu2Name        = Slave2
  (ErrorHandler)
    TimestampMode = Entry  ;timestamp at entry or Change
    ListName1 = "system error"
    ListLen1 = 20
    ListRetain1 = OFF
    ListName2 = error
    ListLen2 = 20
    ListRetain2 = OFF
    ListName3 = warning
    ListLen3 = 20
    ListRetain3 = OFF
    ListName4 = info
    ListLen4 = 20
    ListRetain4 = OFF
  (TelnetServer)
    EnableTelnet = ON  ;start Telnet server
  (SshServer)
    EnableSsh = ON  ;start SSH server
    EnableSftp = ON  ;enable SFTP over SSH
    UseKeyStore = OFF  ;SSH server private key in keystore
    PrivKeyPair = etc/ssh/sshsrvrsa.key  ;if UseKeyStore=OFF, path to SSH server private key file
    KeyId = SshServerRsa  ;if UseKeyStore=ON, name of SSH server private key id
    UserPubKeys =   ;if set e.g. etc/ssh/, path to public key files <user>.pk2 of authorized users
  (NfsServer)
    StartServer = OFF
    Processes = 4  ;number of NFS server tasks
  (FtpServer)
    EnableFtp = ON  ;start FTP Server
    EnableFtps = OFF  ;start FTP Server (TLS enabled)
  (FtpClient)
    UseSsl = OFF  ;use FTPS client
  (SSL)
    SslLibrary = ssl/openssl.o  ;use OpenSSL libary
    EnableSSLv3 = OFF  ;disable SSLv3 support
    EnableTLSv1 = OFF  ;disable TLSv1.0 support
    EnableTLSv1_1 = OFF  ;disable TLSv1.1 support
    EnableTLSv1_2 = ON  ;enable TLSv1.2 support
    EnableTLSv1_3 = ON  ;enable TLSv1.3 support
    SecurityLevel = 0  ;TLS security Level (0..5)
    CipherList =   ;TLS 1.0, 1.1, 1.2 enabled ciphers (e.g. "AES128-SHA:AES256-SHA")
    CipherListFile =   ;TLS 1.0, 1.1, 1.2 enabled ciphers file
    CipherSuites =   ;TLS 1.3 enabled cipher suites (e.g. "TLS_AES_128_GCM_SHA256")
    CipherSuitesFile =   ;TLS 1.3 enabled cipher suites file
    DHParamFile =   ;Diffie-Hellman parameter for DHE ciphersuites
;
; SSL private key/password settings
;
    UseKeyStore = FALSE  ;use VxWorks7 keystore for private keys
    UsePwdVault = FALSE  ;use VxWorks7 password vault for private key passwords
    Password = ********  ;plaintext password for encrypted private key files ... DO NOT USE!
;
; SSL server settings
;
    Cert = ssl/testsrv.crt  ;server PEM-encoded X.509 certificate file
    PrivKey = ssl/testsrv.key  ;server PEM-encoded private key file
    ClientAuth =   ;enable client authentication
    PreferServerCiphers = ON  ;option to prefer the server's cipher preference order
;
; SSL client settings
;
    Cert2 =   ;client PEM-encoded X.509 certificate file
    PrivKey2 =   ;client PEM-encoded private key file
    CAcert =   ;file of concatenated PEM-encoded CA Certificates for server auth
    NoVerifyCert = OFF  ;disable certificate verification of remote SSL server
    VerifyHost = OFF  ;enable hostname verification of remote SSL server
  (SCEP)
  (NfsAuthent)
  (SntpServer)
  (SntpClient)
  (SnmpAgent)
  (PTP)
  (VarAccess)
    VarRightsFile = etc/svi/rights.cfg
  (VarRange)
    VarRangeFile = etc/svi/ranges.cfg
[DRIVERS]
<INCLUDE_PERM =/flash0/app/PROFINET/PN_PRJ1.INI>
  (Card3)
    SlotNb = 3
    StationNb = 1
    Mode = Real
    DriverName = GIO2XX
    CardName = GIO212
    ChanMode1 = TempSensor
    ChanName1 = AV_T_PT100_A_nah_gelb
    TSensor1 = PT100/2
    TsItp1 = 0
    TsFilter1 = 31.2Hz
    LimitAsErrTs1 = 0
    Sync1 = 0
    DisableErr1 = 0
    ChanMode2 = TempSensor
    ChanMode3 = TempSensor
    ChanMode4 = TempSensor
    ChanMode5 = PWM
    ChanMode6 = PWM
    ChanMode7 = PWM
    ChanMode8 = Disabled
    ChanMode9 = Disabled
    ChanMode10 = Disabled
    ChanMode11 = DigitalOut
    ChanMode12 = DigitalOut
    DisableErr2 = 0
    Sync2 = 0
    DisableErr3 = 0
    Sync3 = 0
    Sync4 = 0
    DisableErr4 = 0
    ChanName2 = AV_T_PT100_A_fern_rot
    TSensor2 = PT100/2
    TsItp2 = 0
    TsFilter2 = 31.2Hz
    LimitAsErrTs2 = 0
    ChanName3 = AV_T_PT100_B_nah_blau
    TSensor3 = PT100/2
    TsItp3 = 0
    TsFilter3 = 1kHz
    LimitAsErrTs3 = 0
    ChanName4 = AV_T_PT100_B_fern_schwarz
    TSensor4 = PT100/2
    TsItp4 = 0
    TsFilter4 = 31.2Hz
    LimitAsErrTs4 = 0
    ChanName5 = Heater_A_rot
    DoTypePwm5 = High-Side
    PeriodDur5 = 10000
    RunMode5 = ON
    PwmInvert5 = 0
    DisableErr5 = 0
    ChanName6 = Heater_B_blau
    DoTypePwm6 = High-Side
    PeriodDur6 = 10000
    RunMode6 = ON
    PwmInvert6 = 0
    DisableErr6 = 0
    ChanName7 = FAN
    DoTypePwm7 = High-Side
    PeriodDur7 = 10000
    RunMode7 = ON
    PwmInvert7 = 0
    DisableErr7 = 0
    ChanModeF21 = Disabled
    ChanModeF22 = Disabled
    ChanModeF23 = Disabled
    ChanName11 = DO_QM01
    DoType11 = Push-Pull
    DoInvert11 = 0
    DoImpuls11 = 0
    Sync11 = 0
    DisableErr11 = 0
    ChanName12 = DO_QM02
    DoType12 = Push-Pull
    DoInvert12 = 0
    DoImpuls12 = 0
    Sync12 = 0
    DisableErr12 = 0
    ChanModeF27 = Disabled
    ChanModeF28 = Disabled
  (PNIO)
    Driver = pn202
    StationName = pnio
    Controller = ON
    Device = OFF
    DebugMode = 0
    BootTimeout = 60
    UseSync = OFF
    UseGateway = OFF
    ConfigFile = /flash0/app/PROFINET/PN_CFG.XML
  (MBM1)
    PollingRate = 500
    Priority = 118
    DebugMode = 0
    Protocol = "MODBUS RTU"
    ComDevice = /tyCo/0/1
  (Card1)
    SlotNb = 4
    StationNb = 1
    DriverName = mbm201
    NetMode = Logical
    NetNb = 1
    Mode = Real
    MaxRespTime = 500
    NodeTimeout = 15
    ApplicationConnect = 0
    OptNode = 1
    InitAfterReconnect = 0
    CombReqOfCard = 1
    UseHostName = 0
    SlaveIP = 0.0.0.0
    PortNb = 502
    SlaveAdr = 1
    Channel1 = MBM201.1.ControlMode/U16/rwps/HReg36
    Channel2 = MBM201.1.ModbusAdress/U16/rwps/HReg4010
    Channel3 = MBM201.1.1.4.FMeasure/F32/rwps/HReg41216_2
    Channel4 = MBM201.1.1.4.Temperature/F32/rwps/HReg41272_2
  (Card4)
    SlotNb = 5
    StationNb = 1
    DriverName = mbm201
    NetMode = Logical
    NetNb = 1
    Mode = Real
    MaxRespTime = 500
    NodeTimeout = 15
    ApplicationConnect = 0
    OptNode = 1
    InitAfterReconnect = 0
    CombReqOfCard = 1
    UseHostName = 0
    SlaveIP = 0.0.0.0
    PortNb = 502
    SlaveAdr = 2
    Channel1 = mbm201.1.1.5.ControlMode/U16/rwps/HReg36
    Channel2 = mbm201.1.1.5.ModbusAdress/U16/rwps/HReg4010
    Channel3 = mbm201.1.1.5.Fmeasure/F32/rwps/HReg41216_2
    Channel4 = mbm201.1.1.5.Temperature/F32/rwps/HReg41272_2
    Channel5 = MBM201.1.1.5.Serialnumber/STRING(16)/rwps/HReg61720_8
  (Card5)
    SlotNb = 6
    StationNb = 1
    DriverName = mbm201
    NetMode = Logical
    NetNb = 1
    Mode = Real
    MaxRespTime = 500
    NodeTimeout = 15
    ApplicationConnect = 0
    OptNode = 1
    InitAfterReconnect = 0
    CombReqOfCard = 1
    UseHostName = 0
    SlaveIP = 0.0.0.0
    PortNb = 502
    SlaveAdr = 3
    Channel1 = mbm201.1.1.6.ControlMode/U16/rwps/HReg36
    Channel2 = mbm201.1.1.6.ModbusAdress/U16/rwps/HReg4010
    Channel3 = mbm201.1.1.6.Fmeasure/F32/rwps/HReg41216_2
    Channel4 = mbm201.1.1.6.Temperature/F32/rwps/HReg41272_2
  (Card6)
    SlotNb = 7
    StationNb = 1
    DriverName = mbm201
    NetMode = Logical
    NetNb = 1
    Mode = Real
    MaxRespTime = 500
    NodeTimeout = 15
    ApplicationConnect = 0
    OptNode = 1
    InitAfterReconnect = 0
    CombReqOfCard = 1
    UseHostName = 0
    SlaveIP = 0.0.0.0
    PortNb = 502
    SlaveAdr = 4
    Channel1 = mbm201.1.1.7.ControlMode/U16/rw/HReg36
    Channel2 = mbm201.1.1.7.ModbuAdress/U16/rwps/HReg4010
    Channel3 = mbm201.1.1.7.Fmeasure/F32/rwps/HReg41216_2
    Channel4 = mbm201.1.1.7.Temperature/F32/rwps/HReg41272_2
  (Card7)
    SlotNb = 8
    StationNb = 1
    DriverName = mbm201
    NetMode = Logical
    NetNb = 1
    Mode = Real
    MaxRespTime = 500
    NodeTimeout = 15
    ApplicationConnect = 0
    OptNode = 1
    InitAfterReconnect = 0
    CombReqOfCard = 1
    UseHostName = 0
    SlaveIP = 0.0.0.0
    PortNb = 502
    SlaveAdr = 5
    Channel1 = mbm201.1.1.8.ControlMode/U16/rwps/HReg36
    Channel2 = mbm201.1.1.8.ModbusAddress/U16/rwps/HReg4010
    Channel3 = mbm201.1.1.8.Fmeasure/F32/rw/HReg41216_2
    Channel4 = mbm201.1.1.8.Temperature/F32/rwps/HReg41272_2
  (Card8)
    SlotNb = 9
    StationNb = 1
    DriverName = mbm201
    NetMode = Logical
    NetNb = 1
    Mode = Real
    MaxRespTime = 500
    NodeTimeout = 15
    ApplicationConnect = 0
    OptNode = 1
    InitAfterReconnect = 0
    CombReqOfCard = 1
    UseHostName = 0
    SlaveIP = 0.0.0.0
    PortNb = 502
    SlaveAdr = 6
    Channel1 = mbm201.1.1.9.ControlMode/U16/rwps/HReg36
    Channel2 = mbm201.1.1.9.ModbusAddress/U16/rwps/HReg4010
    Channel3 = mbm201.1.1.9.Fmeasure/F32/rwps/HReg41216_2
    Channel4 = mbm201.1.1.9.Temperature/F32/rwps/HReg41272_2
    Channel5 = MBM201.1.1.9.Serialnumber/STRING(16)/rwps/HReg61720_8
[SERVICES]
  (OPCUAS)
    ServiceName = OPCUAS
    DemoMode = 1
    DebugMode = 0
    Priority = 144
    Role = Server
    Interface = eth0
    UseHostName = 0
    Port = 4840
    Name = "M1 UA Server"
    ApplicationUri = Bachmann:M1UaServer
    ProductUri = http://www.bachmann.info
    PKIDir = PKI/
    PrivateKey = uaserver.pem
    ServerCert = uaserver.der
    CheckClientCert = 0
    MinSamplingRate = 100
    EnableAlarmsHistory = 0
    EnableFileTransfer = 0
<CPU_000>
    ConfigFile = /flash0/opc_config.csv
<CPU_ALL>
[MODBUS]
  (Mappings)
    MappingFile = /flash0/mbm_config.csv
[INTERN_H]
  (BaseParms)
    Partition = 2
    DebugMode = 0x0
    Priority = 93
    ModuleIndex = 0
    ModulePath = /ram0/
    ModuleName = Intern_H.m
